#!/bin/bash

echo "======================================"
echo "Push BioQL Website to GitHub"
echo "======================================"
echo ""
echo "Repository: https://github.com/Bionicsdemo/spectrix.git"
echo "Branch: main"
echo "Commits to push: 3"
echo ""
echo "Commits:"
git log origin/main..HEAD --oneline
echo ""
echo "To push, run ONE of these commands:"
echo ""
echo "Option 1 - If you have SSH key configured:"
echo "  git remote set-url origin git@github.com:Bionicsdemo/spectrix.git"
echo "  git push origin main"
echo ""
echo "Option 2 - Using HTTPS with your GitHub username and Personal Access Token:"
echo "  git push https://YOUR_USERNAME:YOUR_TOKEN@github.com/Bionicsdemo/spectrix.git main"
echo ""
echo "Option 3 - Install GitHub CLI (recommended):"
echo "  brew install gh"
echo "  gh auth login"
echo "  git push origin main"
echo ""
